### ISSUE TITLE
DELETE orders error 질문

### ISSUE THREAD

**Issue by JwahoonKim** [snuwebprogramming-21-1/hw2#8]
order를 취소하려고 delete 요청을 보내는 걸 만들다가 막혀서 질문드립니다.
Api.js의 get함수에서 method만 delete로 바꿔주고 id를 url 끝에 붙여서 요청을 보냈는데 
CORS error, Missing Allow Origin Header 라는 에러가 계속 뜹니다!
검색해봐도 내용을 잘 모르겠습니다 ㅠㅠ
혹시 delete 요청을 보낼때 추가로 필요한 headers 내용이 있는건가요?

**Comment by realcom** [comment]
cors에러가 뜰리가 없는데... 다른분들도 마찬가진가요?

**Comment by realcom** [comment]
수정완료
